require("dotenv").config();
const express = require("express");
const jwt = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
const User = require("../model/User");
const router = express.Router();
const speakeasy = require("speakeasy");
const QRCode = require("qrcode");
const nodemailer = require("nodemailer");

/**
 * @swagger
 * components:
 *   schemas:
 *     Register:
 *       type: object
 *       required:
 *         - name
 *         - email
 *         - password
 *         - country
 *       properties:
 *         name:
 *           type: string
 *           description: The name of the employee
 *         email:
 *           type: string
 *           description: The email of the employee
 *         password:
 *           type: string
 *           description: password
 *         country:
 *           type: string
 *           description: country name
 *       example:
 *         name: Afsar
 *         email: afsar@gmail.com
 *         password: "12345"
 *         country: India
 *
 *     Login:
 *       type: object
 *       required:
 *         - email
 *         - password
 *       properties:
 *         email:
 *           type: string
 *           description: The email of the employee
 *         password:
 *           type: string
 *           description: password
 *       example:
 *         email: afsar@gmail.com
 *         password: "12345"
 *
 *
 *     Mfaverify:
 *       type: object
 *       required:
 *         - email
 *         - mfaToken
 *       properties:
 *         email:
 *           type: string
 *           description: The email of the employee
 *         mfaToken:
 *           type: string
 *           description: Toekn generated by google authenticator app
 *       example:
 *         email: afsar@gmail.com
 *         mfaToken: "123456"
 *
 *     Forget:
 *       type: object
 *       required:
 *         - email
 *       properties:
 *         email:
 *           type: string
 *           description: The email of the employee
 *       example:
 *         email: afsar@gmail.com
 *
 *     Reset:
 *       type: object
 *       required:
 *         - otp
 *         - password
 *         - confirmPassword
 *       properties:
 *         otp:
 *           type: integer
 *           description: 6 digit otp sent to email
 *         password:
 *           type: string
 *           description: new password
 *         confirmPassword:
 *           type: string
 *           description: confirm password
 *       example:
 *         otp: "123456"
 *         password: "1234567890"
 *         confirmPassword: "1234567890"
 *
 *
 *
 */

/**
 * @swagger
 * tags:
 *   name: Auth
 *   description: Authentication and registaration of user
 */

/**
 * @swagger
 * /user/login:
 *   post:
 *     summary: Login
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Login'
 *     responses:
 *       200:
 *         description: The User will redirect to google auth
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Login'
 *       500:
 *         description: Some server error
 */
router.post("/login", async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    console.log(user);
    if (!user) {
      return res.status(401).json({ error: "Invalid credentials" });
    }
    const matchPassword = await bcrypt.compare(password, user.password);
    if (matchPassword) {
      res.json({ message: "Login successful", qrCodeUrl: user.qrCodeUrl });
    } else {
      res.status(401).json({ error: "Invalid credentials" });
    }
  } catch (error) {
    console.error("Error during login:", error);
    res.status(500).json({ error: "Login failed" });
  }
});

/**
 * @swagger
 * /user/signup:
 *   post:
 *     summary: Register
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Register'
 *     responses:
 *       200:
 *         description: The User was successfully created
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Register'
 *       500:
 *         description: Some server error
 */
router.post("/signup", async (req, res) => {
  try {
    const userData = req.body;
    const hashedPassword = await bcrypt.hash(userData.password, 10);

    const user = await User.findOne({ email: userData.email });

    if (user) {
      return res.status(200).json({ error: "Email is already register." });
    }

    const mfaSecret = speakeasy.generateSecret({
      length: 20,
      name: "employee-manager",
    });

    const newUser = new User({
      name: userData.name,
      email: userData.email,
      password: hashedPassword,
      country: userData.country,
      mfaSecret: mfaSecret.base32,
    });

    await newUser.save();

    // Generate a QR code for the user to scan
    const qrCode = await QRCode.toDataURL(mfaSecret.otpauth_url);
    res.status(200).json({ newUser, qrCodeUrl: qrCode });
    console.log("Secret Key:", mfaSecret.base32);
    console.log("QR Code Image URL:", qrCode);
  } catch (error) {
    console.error("Error creating a new user:", error);
    res.status(500).json({ error: "Failed to create a new user" });
  }
});

/**
 * @swagger
 * /user/mfa-verify:
 *   post:
 *     summary: Authenticate user by google authenticator app
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Mfaverify'
 *     responses:
 *       200:
 *         description: The User will redirect to google auth
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Mfaverify'
 *       500:
 *         description: Some server error
 */

router.post("/mfa-verify", async (req, res) => {
  try {
    const { email, mfaToken } = req.body;
    const user = await User.findOne({ email });
    if (!user) {
      return res.status(401).json({ error: "Invalid credentials" });
    }
    console.log(JSON.stringify(user));
    var token = speakeasy.totp({
      secret: user.mfaSecret,
      encoding: "base32",
    });
    console.log("Token is ", token);
    console.log(`mfaTOken is ${mfaToken} and secret is ${user.mfaSecret}`);
    const verified = speakeasy.totp.verify({
      secret: user.mfaSecret,
      encoding: "base32",
      token: mfaToken,
    });
    console.log("verified is ", verified);
    if (verified) {
      const jwtFToken = jwt.sign({ email: user.email }, process.env.JWT_TOKEN, {
        expiresIn: "20m",
      });
      console.log("token", jwtFToken);
      res.json({ message: "Verification successful", jwtToken: jwtFToken });
    } else {
      res.status(401).json({ error: "Invalid token" });
    }
  } catch (errorundefined) {
    console.error("Error during verification:", errorundefined);
    res.status(500).json({ error: "Verification failed" });
  }
});

/**
 * @swagger
 * /user/forgot-password:
 *   post:
 *     summary: Forget password.
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Forget'
 *     responses:
 *       200:
 *         description: It will send OTP to registered email id.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Forget'
 *       500:
 *         description: Some server error
 */

router.post("/forgot-password", async (req, res) => {
  try {
    const { email } = req.body;
    const user = await User.findOne({ email });

    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }
    // generate otp
    const resetToken = Math.floor(100000 + Math.random() * 900000).toString();
    user.resetPasswordToken = resetToken;
    user.resetPasswordExpires = Date.now() + 5 * 60 * 1000; // 5 min expiry

    await user.save();

    // send mail
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: "chinmaybondev2@gmail.com",
        pass: "wzjx cfxu gavr wydm",
      },
    });

    const mailOptions = {
      from: "chinmaybondev2@gmail.com",
      to: email,
      subject: "Password Reset",
      text: `Hi, Your OTP for password reset is: ${resetToken}`,
    };

    transporter.sendMail(mailOptions, (error, info) => {
      if (error) {
        console.error("Error sending email:", error);
        return res.status(500).json({
          error: "Failed to send reset token",
          errorMessage: error.message,
        });
      }
      console.log("Email sent:", info.response);
      res.status(200).json({ message: "Reset token sent to your email" });
    });
  } catch (error) {
    console.error("Error during forgot password:", error);
    res.status(500).json({ error: "Forgot password failed" });
  }
});

/**
 * @swagger
 * /user/reset-password:
 *   post:
 *     summary: Reset password.
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Reset'
 *     responses:
 *       200:
 *         description: To reset password
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Reset'
 *       500:
 *         description: Some server error
 */

router.post("/reset-password", async (req, res) => {
  try {
    const { otp, password, confirmPassword } = req.body;

    if (!otp || !password || !confirmPassword) {
      return res
        .status(400)
        .json({ error: "Please provide OTP and new password" });
    }

    if (password !== confirmPassword) {
      return res.status(400).json({ error: "Passwords do not match" });
    }

    const user = await User.findOne({ resetPasswordToken: otp });

    if (!user || user.resetPasswordExpires < Date.now()) {
      return res.status(404).json({ error: "Invalid or expired OTP" });
    }

    const hashedPassword = await bcrypt.hash(password, 10);
    user.password = hashedPassword;
    user.resetPasswordToken = undefined;
    user.resetPasswordExpires = undefined;

    await user.save();

    res.status(200).json({ message: "Password reset successfully" });
  } catch (error) {
    console.error("Error resetting password:", error);
    res.status(500).json({ error: "Failed to reset password" });
  }
});
module.exports = router;
