require("dotenv").config();
const express = require("express");
const jwt = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
const nodemailer = require("nodemailer");
const QRCode = require("qrcode");
const speakeasy = require("speakeasy");
const User = require("../model/User");

const {
  loginUser,
  registerUser,
  mfaVerifyUser,
  forgetUser,
  resetUser,
} = require("../controllers/AuthController");

const router = express.Router();

/**
 * @swagger
 * components:
 *   schemas:
 *     Register:
 *       type: object
 *       required:
 *         - name
 *         - email
 *         - password
 *         - country
 *       properties:
 *         name:
 *           type: string
 *           description: The name of the employee
 *         email:
 *           type: string
 *           description: The email of the employee
 *         password:
 *           type: string
 *           description: password
 *         country:
 *           type: string
 *           description: country name
 *       example:
 *         name: Afsar
 *         email: afsar@gmail.com
 *         password: "12345"
 *         country: India
 *
 *     Login:
 *       type: object
 *       required:
 *         - email
 *         - password
 *       properties:
 *         email:
 *           type: string
 *           description: The email of the employee
 *         password:
 *           type: string
 *           description: password
 *       example:
 *         email: afsar@gmail.com
 *         password: "12345"
 *
 *
 *     Mfaverify:
 *       type: object
 *       required:
 *         - email
 *         - mfaToken
 *       properties:
 *         email:
 *           type: string
 *           description: The email of the employee
 *         mfaToken:
 *           type: string
 *           description: Toekn generated by google authenticator app
 *       example:
 *         email: afsar@gmail.com
 *         mfaToken: "123456"
 *
 *     Forget:
 *       type: object
 *       required:
 *         - email
 *       properties:
 *         email:
 *           type: string
 *           description: The email of the employee
 *       example:
 *         email: afsar@gmail.com
 *
 *     Reset:
 *       type: object
 *       required:
 *         - otp
 *         - password
 *         - confirmPassword
 *       properties:
 *         otp:
 *           type: integer
 *           description: 6 digit otp sent to email
 *         password:
 *           type: string
 *           description: new password
 *         confirmPassword:
 *           type: string
 *           description: confirm password
 *       example:
 *         otp: "123456"
 *         password: "1234567890"
 *         confirmPassword: "1234567890"
 */

/**
 * @swagger
 * tags:
 *   name: Auth
 *   description: Authentication and registaration of user
 */

/**
 * @swagger
 * /user/login:
 *   post:
 *     summary: Login
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Login'
 *     responses:
 *       200:
 *         description: The User will redirect to google auth
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Login'
 *       500:
 *         description: Some server error
 */
router.post("/login", loginUser);

/**
 * @swagger
 * /user/signup:
 *   post:
 *     summary: Register
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Register'
 *     responses:
 *       200:
 *         description: The User was successfully created
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Register'
 *       500:
 *         description: Some server error
 */
router.post("/signup", registerUser);

/**
 * @swagger
 * /user/mfa-verify:
 *   post:
 *     summary: Authenticate user by google authenticator app
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Mfaverify'
 *     responses:
 *       200:
 *         description: The User will redirect to google auth
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Mfaverify'
 *       500:
 *         description: Some server error
 */

router.post("/mfa-verify", mfaVerifyUser);

/**
 * @swagger
 * /user/forgot-password:
 *   post:
 *     summary: Forget password.
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Forget'
 *     responses:
 *       200:
 *         description: It will send OTP to registered email id.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Forget'
 *       500:
 *         description: Some server error
 */

router.post("/forgot-password", forgetUser);

/**
 * @swagger
 * /user/reset-password:
 *   post:
 *     summary: Reset password.
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Reset'
 *     responses:
 *       200:
 *         description: To reset password
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Reset'
 *       500:
 *         description: Some server error
 */

router.post("/reset-password", resetUser);

module.exports = router;
